apache/syncope

src/main/asciidoc/getting-started/obtain.adoc
The JAVA_OPTS in the Debian instructions appears to be missing a line-continuation symbol ('\\') at the end of the second line.
=> Missing line-continuation symbol

client/idrepo/console/src/main/java/org/apache/syncope/client/console/commons/Constants.java, client/idrepo/console/src/main/resources/org/apache/syncope/client/console/pages/BasePage.html
Best security practise is to add rel="noopener noreferrer" for links that usestarget="_blank". See for example: https://dev.to/ben/the-targetblank-vulnerability-by-example
=> Add noopener noreferrer for target blank URLs

client/console/src/main/java/org/apache/syncope/client/console/SyncopeConsoleApplication.java, client/enduser/src/main/java/org/apache/syncope/client/enduser/SyncopeEnduserApplication.java
It's good security practice to enable the HTTP headers included in the patch. See here:
https://ci.apache.org/projects/wicket/guide/8.x/single.html#_external_security_checks
I created the PR against 2.1.x, as I'm not sure what state master is currently in.
=> Enable security-related HTTP headers in the console

pom.xml
See https://issues.apache.org/jira/browse/SYNCOPE-1483
Switching to 3.0.0.M2 version of plugin allows for a successful build.
=> SYNCOPE-1483: maven-enforcer-plugin: API incompatibility fails the build

pom.xml
Coordinates show that the current available release version is RELEASE111.
See https://issues.apache.org/jira/browse/SYNCOPE-1484
Related: https://issues.apache.org/jira/browse/SYNCOPE-1464
=> [SYNCOPE-1484]: syncope-ide-netbeans submodule fails to find netbeans dependency

ide/netbeans/src/main/java/org/apache/syncope/ide/netbeans/view/ServerDetailsView.java, pom.xml, src/main/resources/org/apache/syncope/checkstyle.xml
See https://issues.apache.org/jira/browse/SYNCOPE-1486
- Upgrade Checkstyle version
- Re-adjust configuration to locate the right parent for the LineLength check
- Fix instances where line length was violated
- Limit scans to java and xml files to avoid messing up encodings for language bundles.
=> SYNCOPE-1486: upgrade checkstyle; fix syntax issues and line lengths

fit/console-reference/pom.xml, fit/core-reference/pom.xml, fit/core-reference/src/main/resources/oracle/Dockerfile, fit/enduser-reference/pom.xml, pom.xml
- The Oracle database client is now available in Maven Central. This pull request updates the coordinates.
- Docker-based tests for Oracle are switched to use Oracle enterprise edition 12g (the slim variant of the image)
- Timeouts are increased to account for updates and startup time.
=> NOJIRA: Update Oracle db client dependency coordinates; increase timeouts

core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/task/PullTask.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/task/JPAPullTask.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/TaskDataBinderImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/propagation/PriorityPropagationTaskExecutor.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/DefaultRealmPullResultHandler.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/utils/ConnObjectUtils.java
This pull request fixes a typo in `getDestinatioRealm` where it should be `getDestinationRealm` (missing `n`).
=> NOJIRA: Fix typo in destination field

common/lib/src/main/java/org/apache/syncope/common/lib/to/AuditEntryTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/AuditTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/types/StandardEntitlement.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/beans/AuditQuery.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/service/AuditService.java, core/logic/src/main/java/org/apache/syncope/core/logic/AuditLogic.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/dao/AuditDAO.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/AuditEntry.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/JPAAuditDAO.java, core/persistence-jpa/src/test/resources/domains/MasterContent.xml, core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/AuditEntryImpl.java, core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/data/AuditDataBinder.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/DefaultAuditManager.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/AuditDataBinderImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/job/report/AuditReportlet.java, core/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AbstractAnyService.java, core/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AuditServiceImpl.java, fit/core-reference/pom.xml, fit/core-reference/src/test/java/org/apache/syncope/fit/AbstractITCase.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/AuditITCase.java
This pull request demonstrates the basic outline of introduced components and the design, modeled and inspired by existing functionality/components in Syncope. This is still very much a WIP and will be updated continuously.
A brief outline of the changes are:
1. AuditService as the main REST API interface, presenting search ops
2. AuditLogic in charge of executing search ops, etc.
3. AuditDAO and AuditDataBinder, in charge of handling the JPA layer and data bindings.
4. AuditTO, AuditEntry and AuditEntryImpl as carrier/transfer objects between the data layer, core and APIs.
=> SYNCOPE-1511: Provide Audit APIs

ext/oidcclient/agent/pom.xml, ext/saml2sp/agent/pom.xml, pom.xml, standalone/LICENSE
The JSTL dependency is not needed and comes with a CVE as it ships with an old version of Apache TagLibs.
=> Replace JSTL with Apache Standard Taglibs

pom.xml
This is to fix the CVE: tika-core-1.21.jar (pkg:maven/org.apache.tika/tika-core@1.21, cpe:2.3:a:apache:tika:1.21:*:*:*:*:*:*:*) : CVE-2019-10088, CVE-2019-10093, CVE-2019-10094
Please cherry-pick to 2.1 + 2.0
=> Updating Tika

common/lib/src/main/java/org/apache/syncope/common/lib/patch/ResourceDeassociationPatch.java, common/lib/src/main/java/org/apache/syncope/common/lib/policy/PasswordPolicyTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/policy/PolicyTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/AccessTokenTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/AnyTypeTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/ConnInstanceTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/ConnPoolConfTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/ItemTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/MailTemplateTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/MappingTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/OrgUnitTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/ProvisionTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/RealmTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/ResourceTO.java, common/lib/src/main/java/org/apache/syncope/common/lib/to/RoleTO.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/beans/AbstractQuery.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/beans/AnyQuery.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/beans/ExecQuery.java, common/rest-api/src/main/java/org/apache/syncope/common/rest/api/beans/SchemaQuery.java
Override equals and hashCode methods to preserve the backward compatibility with 2.0.X
=> [SYNCOPE-1533] added equals and hashCode methods for TOs

client/console/src/main/java/org/apache/syncope/client/console/wizards/any/AbstractAttrs.java, core/logic/src/main/java/org/apache/syncope/core/logic/ReconciliationLogic.java, core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/PlainAttrTest.java, core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/SecurityQuestionTest.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/MappingManagerImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/UserDataBinderImpl.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/AuthDataAccessor.java, ext/saml2sp/logic/src/main/java/org/apache/syncope/core/logic/saml2/SAML2UserManager.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/PushTaskITCase.java
This pull request:
- Removes a number of unused imports from Syncope
- Primarily makes sure, in certain areas, that Optional objects are checked to actually contain a value before a value can be retrieved. I specifically ran into an example of this, as a result of bad (manual) mapping configuration in the MasterContent.xml file, where no mapping was tagged with a `conn-object-key=1`. I decided to add a bit more safety to protect and defect against the dark arts...of dealing with optionals! :)
=> Check for presence of value before using an Optional

client/console/src/main/java/org/apache/syncope/client/console/panels/UserDirectoryPanel.java
Removes the "manage history" action menu items and only displays it when the parent wizard is in model view.
Easier link for comparisons:
https://github.com/apache/syncope/pull/163/files?w=1
=> SYNCOPE-1511: only show history management action menu when wizard is in modal mode

.travis.yml, pom.xml
The Travis CI trusty image is deprecated. This change switches the distro to Bionic which builds against Ubuntu 18.
PS. I also experimented with arm-based builds which are super fast to startup (less than 10 seconds) but they are not as packed as others (No maven, Java installed, etc) and the cache seems somewhat suspicious with those. Bionic should do fine for now.
=> NOJIRA - Switch Travis CI to AMD64 Bionic Distro

.travis.yml
After fixing [SYNCOPE-1564](https://issues.apache.org/jira/browse/SYNCOPE-1564) we are ready to add YAML-based integration tests to the collection run by Travis CI.
=> Enabling YAML-based IT run

common/am/lib/src/main/java/org/apache/syncope/common/lib/to/OIDCJWKSTO.java, common/am/lib/src/main/java/org/apache/syncope/common/lib/types/AMEntitlement.java, common/am/rest-api/src/main/java/org/apache/syncope/common/rest/api/service/OIDCJWKSConfService.java, common/am/rest-api/src/main/java/org/apache/syncope/common/rest/api/service/wa/OIDCJWKSService.java, core/am/logic/src/main/java/org/apache/syncope/core/logic/GoogleMfaAuthAccountLogic.java, core/am/logic/src/main/java/org/apache/syncope/core/logic/GoogleMfaAuthTokenLogic.java, core/am/logic/src/main/java/org/apache/syncope/core/logic/OIDCJWKSLogic.java, core/am/logic/src/main/java/org/apache/syncope/core/logic/SAML2IdPMetadataLogic.java, core/am/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/OIDCJWKSConfServiceImpl.java, core/am/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/wa/OIDCJWKSServiceImpl.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/dao/auth/OIDCJWKSDAO.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/auth/OIDCJWKS.java, core/persistence-jpa-json/pom.xml, core/persistence-jpa/pom.xml, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/auth/JPAOIDCJWKSDAO.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/JPAEntityFactory.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/auth/JPAOIDCJWKS.java, core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/OIDCJWKSTest.java, core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/data/OIDCJWKSDataBinder.java, core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/data/SAML2IdPMetadataDataBinder.java, core/provisioning-java/pom.xml, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/OIDCJWKSDataBinderImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/SAML2IdPMetadataDataBinderImpl.java, fit/core-reference/src/test/java/org/apache/syncope/fit/AbstractITCase.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/OIDCJWKSConfITCase.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/OIDCJWKSITCase.java, pom.xml, wa/starter/pom.xml, wa/starter/src/main/java/org/apache/syncope/wa/starter/config/SyncopeWAConfiguration.java, wa/starter/src/main/java/org/apache/syncope/wa/starter/oidc/SyncopeWAOIDCJWKSGeneratorService.java
- Allows Syncope to manage the JWKS store via REST endpoints
- Uses the `nimbus-jose-jwt` library to generate keys with algorithm RSA and length 2048
- Provides two sets of APIs; one to be invoked by the admin console for delete/update tasks and the other may be used by WA. (Permissions are kept separate)
- Adds tests and integration tests.
=> SYNCOPE-1556: Manage OIDC JWKS

.travis.yml, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/batch/BatchItemRequest.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/ProvisioningContext.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/job/notification/DefaultNotificationJobDelegate.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/AuthDataAccessor.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/JWTAuthentication.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/JWTAuthenticationFilter.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/JWTAuthenticationProvider.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/UsernamePasswordAuthenticationProvider.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/WebSecurityContext.java, ext/self-keymaster/client/src/main/java/org/apache/syncope/common/keymaster/client/self/SelfKeymasterServiceOps.java, ext/self-keymaster/rest-api/src/main/java/org/apache/syncope/ext/self/keymaster/api/service/NetworkServiceService.java, ext/self-keymaster/rest-cxf/src/main/java/org/apache/syncope/ext/self/keymaster/cxf/service/NetworkServiceServiceImpl.java, fit/build-tools/pom.xml, fit/console-reference/src/main/webapp/WEB-INF/payara-web.xml, fit/core-reference/pom.xml, fit/core-reference/src/main/webapp/WEB-INF/payara-web.xml, fit/core-reference/src/test/resources/mail.properties, fit/enduser-reference/src/main/webapp/WEB-INF/payara-web.xml, pom.xml
Finally, restoring compatibility with Payara Server 5.
=> Making Payara working again

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/OIDCJWKSDataBinderImpl.java, fit/wa-reference/src/main/resources/wa.properties
1. Fixes issues with OIDC JWKS generation, set to include private key and algorithm
2. Updates `wa.properties` for `wa-reference`  module to better match the given WA setup.
With these changes, and most recent CAS snapshot (WIP), OIDC functionality is restored back to normal.
=> NOJIRA: Fix OIDC JWKS generation and properties

docker/wa/src/main/resources/wa.properties, fit/wa-reference/src/main/resources/wa.properties, pom.xml, wa/starter/pom.xml, wa/starter/src/main/java/org/apache/syncope/wa/starter/config/SyncopeWAConfiguration.java, wa/starter/src/main/resources/application.properties, wa/starter/src/test/resources/dev/wa.properties
This pull request adjusts WA to turn on Swagger support via the `cas-server-support-swagger` dependency. In doing so,
1. The [CAS module is upgraded](https://apereo.github.io/cas/development/integration/Swagger-Integration.html) to base its swagger support on top of Swagger v2.1.x
2. The WA configuration does a simple bean override to present Syncope information to the Docklet, such as version, title, etc.
3. Default configuration is adjusted to consider actuators, controllers etc as part of Swagger UI.
=> SYNCOPE-1545: Enable Swagger support for WA

pom.xml
This should be followed up with RC5 in late Nov with the final 6.3 GA release by late Dec, if not earlier.
=> NOJIRA: upgrade WA to build against 6.3 RC4

client/idrepo/console/src/main/java/org/apache/syncope/client/console/panels/UserDirectoryPanel.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/OIDCJWKSDataBinderImpl.java, docker/wa/src/main/resources/application.properties, fit/build-tools/src/main/java/org/apache/directory/server/core/normalization/NormalizationInterceptor.java, fit/build-tools/src/main/java/org/apache/syncope/fit/buildtools/cxf/DateParamConverterProvider.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/UserSelfITCase.java, fit/wa-reference/pom.xml, pom.xml, sra/src/main/java/org/apache/syncope/sra/SecurityConfig.java, sra/src/main/java/org/apache/syncope/sra/security/oauth2/OAuth2SecurityConfigUtils.java, sra/src/main/java/org/apache/syncope/sra/security/oauth2/OAuth2SessionRemovalServerLogoutHandler.java, wa/pom.xml, wa/starter/pom.xml, wa/starter/src/main/java/org/apache/syncope/wa/starter/mapping/OIDCRPTOMapper.java, wa/starter/src/main/resources/application.properties, wa/starter/src/test/resources/debug/application-debug.properties
By this upgrade, we can also upgrade Spring Boot and Spring Cloud Gateway to latest releases, thus removing the need of different dependency versions for JDK 16.
=> Upgrading CAS to 6.4.0-SNAPSHOT

.travis.yml, ext/saml2sp4ui/logic/src/main/java/org/apache/syncope/core/logic/saml2/SAML2ClientCache.java
This is an attempt to allow Travis CI run painfully the integration tests under `fit/wa-reference`
=> Splitting wa-reference test classes into separate runs on Travis

wa/starter/src/main/java/org/apache/syncope/wa/starter/SyncopeWAApplication.java, wa/starter/src/test/java/org/apache/syncope/wa/starter/AbstractTest.java
When running with initializr in separate servlet container, session tracking modes are left to their defaults and `SessionConfiguringInitializer` backs away, as it only affects embedded servlet containers. This makes both COOKIE and URL modes available to the underlying response, which cause very strange behavior with URL encoding and inclusion of `jsessionid` in the URL, which in turn causes Spring Security to block the request as it sees `;` as a malicious character.
In this patch, the behavior for `SessionConfiguringInitializer` is partially emulated to set the session tracking modes based on configured application properties.
=> Auto-configure session tracking modes

core/spring/src/main/java/org/apache/syncope/core/spring/ImplementationManager.java
=> [SYNCOPE-1635] Use singleton bean for each domain for each rule with conf

core/rest-cxf/src/main/resources/META-INF/web-fragment.xml
As Syncope 2.1.x is stuck on CXF 3.2.x, it is vulnerable to:
http://cxf.apache.org/security-advisories.data/CVE-2020-13954.txt.asc
I confirmed with this PR you can no longer see the services page (http://localhost:9080/syncope/rest/services)
=> Disable CXF Services Listing

client/idm/console/src/main/java/org/apache/syncope/client/console/rest/ConnectorRestClient.java, client/idm/console/src/main/java/org/apache/syncope/client/console/status/LinkedAccountStatusPanel.java, client/idm/console/src/main/java/org/apache/syncope/client/console/wizards/any/LinkedAccountPlainAttrsPanel.java, client/idm/console/src/main/java/org/apache/syncope/client/console/wizards/resources/ResourceProvisionPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/wizards/WizardMgtPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/wizards/any/AbstractAttrsWizardStep.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/wizards/any/AnyWizardBuilder.java, client/idrepo/enduser/src/main/java/org/apache/syncope/client/enduser/panels/AnyFormPanel.java, core/idm/logic/src/main/java/org/apache/syncope/core/logic/ReconciliationLogic.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/SyncopeOpenApiCustomizer.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/search/FilterVisitor.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/search/SearchCondVisitor.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/JPAAnyMatchDAO.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/notification/DefaultNotificationManager.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/propagation/AbstractPropagationTaskExecutor.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/propagation/PropagationManagerImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/DefaultUserPullResultHandler.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/DefaultUserPushResultHandler.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/InboundMatcher.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/OutboundMatcher.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/utils/TemplateUtils.java, ext/saml2sp4ui/logic/src/main/java/org/apache/syncope/core/logic/saml2/SAML2ClientCache.java, fit/build-tools/src/main/java/org/apache/syncope/fit/buildtools/cxf/UserServiceImpl.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/SearchITCase.java
- Simplify `if(Optional.isPresent())` that can be rewritten in the functional style.
- Simplify optional call chains to use `isPresent()` or `isEmpty()` correctly.
A more accurate description of changes can be seen at: https://github.com/apache/syncope/pull/284/files?w=1
=> Clean up: Simplify optional call chains

wa/starter/src/main/java/org/apache/syncope/wa/starter/config/SyncopeWAConfiguration.java
This pull request turns off and disables CGLIB bean proxying for the WA module. This is the recommended practice from Spring which would help WA in the future to compile better and easier against GraalVM. Without bean proxying, bean methods can no longer call each other directly during construction, as there is no proxy to intercept. Instead, references either need to be passed as auto-wired parameters (the approach used here), or they need to be injected into configuration classes using injections. (The latter approach is generally more preferable, if the number of injected parameters grows unwieldy) 
Also fixes a bean name typo (missing `e`).
This approach might also be used for #287 as well.
=> NOJIRA - Turn off bean proxying for WA; fixes typo

archetype/pom.xml, fit/build-tools/pom.xml, pom.xml
see https://issues.apache.org/jira/browse/SYNCOPE-1723
this PR fixes one source of non-reproducible bits
for full path in properties, it would be easy to change value in pom.xml https://github.com/apache/syncope/blob/master/pom.xml#L513 to drop the absolute path, but I don't know if this will break for the builder: what i doubt is that people consuming the resulting artifact can use the value, because the path does not point to anything useful beyond the builder
=> SYNCOPE-1723 remove non-reproducible entries from git.properties

pom.xml
https://maven.apache.org/pom.html#Licenses
"Using an [SPDX identifier](https://spdx.org/licenses/) as the license name is recommended."
=> Switch to SPDX identifier for the license

core/provisioning-java/pom.xml, core/spring/pom.xml, core/spring/src/main/java/org/apache/syncope/core/spring/security/MSEntraJWTSSOProvider.java, core/spring/src/main/java/org/apache/syncope/core/spring/security/jws/MSEntraAccessTokenJWSVerifier.java, core/spring/src/test/java/org/apache/syncope/core/spring/security/MSEntraJWTSSOProviderTest.java, core/spring/src/test/java/org/apache/syncope/core/spring/security/jws/MSEntraAccessTokenJWSVerifierTest.java
Microsoft Entra uses self-issued access tokens, e.g. for SCIM provisioning requests, to authenticate on external systems. To authorise these requests in Syncope, they must be verified against public keys published by Microsoft in a JSON Web Key Set (JWKS).
This PR adds a `MSEntraAccessTokenJWSVerifier` implementation, which loads a JWKS provided by Microsoft from the corresponding endpoint, caches the public keys for the recommended duration and refetches them afterwards. The `MSEntraJWTSSOProvider` implementation allows to verify and authorize requests coming from Microsoft Entra based on the JSON Web Token (JWT) sent along in the request header.
=> [SYNCOPE-1796] Implemented verification of access tokens issued by Microsoft Entra (formerly Azure)

ext/scimv2/logic/pom.xml, ext/scimv2/logic/src/main/java/org/apache/syncope/core/logic/SCIMDataBinder.java, ext/scimv2/logic/src/test/java/org/apache/syncope/core/logic/SCIMDataBinderTest.java
Following the [SCIM 2.0 specification](https://www.rfc-editor.org/rfc/rfc7643#section-4.1.1), the singular attribute `active` is specified of type Boolean. Deviating from this, some cloud providers (namely Microsoft Entra) on PATCH requests send this as a string value of `"True"` or `"False"`. 
To ensure compatibility, with this PR string representations (`"true"` and `"false"`, case insensitive) also get interpreted as Boolean values.
(Apache id: philipp-trenz)
=> [SYNCOPE-1797] Compatibility of SCIM 2.0 requests from Microsoft Entra

common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/AuthModuleConf.java, common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/JcifsSpnegoAuthModuleConf.java, wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/mapping/AuthModulePropertySourceMapper.java
=> [SYNCOPE-1816] JcifsSpnegoAuthentication

pom.xml
3 CVEs detected on this branch needed an fix. 
Upgrade to cxf 3.5.6 , spring 5.3.33 , spring security to 5.7.12 and owasp-java-html-sanitizer to 20211018.1 fix them.
Unit tests are stable, and our integration tests did not show regression.
=> Update CXF, Spring Framework and Security dependencies to fix CVEs

.github/workflows/mariadb.yml, core/persistence-jpa-json/pom.xml, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/MaJPAJSONPersistenceContext.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/AbstractJPAJSONAnyDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/MaJPAJSONAnyDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/MaJPAJSONAnySearchDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/MaJPAJSONAuditConfDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/MaJPAJSONPlainSchemaDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/MyJPAJSONAnyDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/PGJPAJSONAnyDAO.java, core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/entity/MaJPAJSONEntityFactory.java, core/persistence-jpa-json/src/main/resources/META-INF/spring-orm-majson.xml, core/persistence-jpa-json/src/main/resources/audit/audit_majson.sql, core/persistence-jpa-json/src/main/resources/core-majson.properties, core/persistence-jpa-json/src/main/resources/majson/indexes.xml, core/persistence-jpa-json/src/main/resources/majson/views.xml, core/persistence-jpa-json/src/test/java/org/apache/syncope/core/persistence/jpa/JPAJSONTestContextCustomizer.java, core/persistence-jpa-json/src/test/resources/core-majson-test.properties, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/AbstractAnyDAO.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/JPAAnySearchDAO.java, core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/UserTest.java, docker/core/src/main/resources/core-majson.properties, docker/src/main/resources/docker-compose/docker-compose-majson.yml, fit/core-reference/pom.xml, fit/core-reference/src/main/resources/core-majson.properties, src/main/asciidoc/reference-guide/configuration/dbms.adoc, src/site/xdoc/building.xml
The JSON support for MariaDB is introduced with a couple of limitations:
1. [MDEV-27898](https://jira.mariadb.org/browse/MDEV-27898): user `root` is needed
2. [MDEV-34644](https://jira.mariadb.org/browse/MDEV-34644): the search views cannot be created as done for MySQL, hence search operations are not implemented by full leveraging JSON features
=> [SYNCOPE-1662] Introducing JSON support for MariaDB

common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/LDAPAuthModuleConf.java, wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/mapping/AuthModulePropertySourceMapper.java
See https://issues.apache.org/jira/browse/SYNCOPE-1835
PS Also fixes a small bug wrt to collecting the DN attribute.
=> SYNCOPE-1835: Support Credential Criteria for LDAP authentication

client/am/console/src/main/java/org/apache/syncope/client/console/authprofiles/AuthProfileItemDirectoryPanel.java, client/idm/console/src/main/java/org/apache/syncope/client/console/panels/ConnectorDirectoryPanel.java, client/idm/console/src/main/java/org/apache/syncope/client/console/panels/ResourceDirectoryPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/events/SelectedEventsPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/panels/DirectoryPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/panels/ListViewPanel.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/panels/search/SearchUtils.java, client/idrepo/console/src/main/java/org/apache/syncope/client/console/wizards/any/UserTemplateWizardBuilder.java, client/idrepo/enduser/src/main/java/org/apache/syncope/client/enduser/SyncopeEnduserSession.java, common/idrepo/lib/src/main/java/org/apache/syncope/common/lib/EntityTOUtils.java, common/idrepo/lib/src/main/java/org/apache/syncope/common/lib/jackson/SyncopeJsonMapper.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/search/FilterVisitor.java, core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/search/SearchCondVisitor.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/AbstractEntity.java, core/persistence-neo4j/src/main/java/org/apache/syncope/core/persistence/neo4j/entity/AbstractNode.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/TaskDataBinderImpl.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/propagation/DefaultPropagationManager.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/utils/ConnObjectUtils.java, ext/elasticsearch/client-elasticsearch/src/main/java/org/apache/syncope/ext/elasticsearch/client/ElasticsearchIndexManager.java, ext/flowable/flowable-bpmn/src/main/java/org/apache/syncope/core/flowable/impl/FlowableUserRequestHandler.java, ext/flowable/flowable-bpmn/src/main/java/org/apache/syncope/core/flowable/support/SyncopeFormHandlerHelper.java, ext/opensearch/client-opensearch/src/main/java/org/apache/syncope/ext/opensearch/client/OpenSearchIndexManager.java, ext/scimv2/logic/src/main/java/org/apache/syncope/core/logic/SCIMDataBinder.java, ext/scimv2/scim-rest-cxf/src/main/java/org/apache/syncope/ext/scimv2/cxf/SCIMExceptionMapper.java, fit/core-reference/src/main/java/org/apache/syncope/fit/core/reference/TestFileAuditProcessor.java, wa/starter/src/main/java/org/apache/syncope/wa/starter/mapping/AbstractClientAppMapper.java
This pull request replaces instanceof checks with that of pattern matching, and also updates other smaller constructs to use newer features of JDK and APIs when it comes to writing file output, etc.
=> NOJIRA: Replace instanceof checks with pattern matching

ext/flowable/flowable-bpmn/src/main/java/org/apache/syncope/core/flowable/impl/FlowableUserWorkflowAdapter.java
allow propagation to external resources after form validation
=> [SYNCOPE-1854] Propagate changes for user update while pending approval

core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/RESTProperties.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AccessTokenServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AnyObjectServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AnyTypeClassServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AnyTypeServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AuditServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/CommandServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/DelegationServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/DynRealmServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/FIQLQueryServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/GroupServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/ImplementationServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/MailTemplateServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/NotificationServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/PolicyServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/RealmServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/RelationshipTypeServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/ReportServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/RoleServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/SchemaServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/SecurityQuestionServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/SyncopeServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/TaskServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/UserSelfServiceImpl.java, core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/UserServiceImpl.java
This pull request removes the `@Service` annotation from implementations that are explicitly created as beans.
=> Chore: remove service annotation from spring beans

client/am/console/src/main/resources/org/apache/syncope/client/console/authprofiles/AuthProfileDirectoryPanel.properties, client/am/console/src/main/resources/org/apache/syncope/client/console/authprofiles/AuthProfileDirectoryPanel_fr_CA.properties, client/am/console/src/main/resources/org/apache/syncope/client/console/authprofiles/AuthProfileDirectoryPanel_ja.properties, client/am/console/src/main/resources/org/apache/syncope/client/console/authprofiles/AuthProfileDirectoryPanel_pt_BR.properties, client/am/console/src/main/resources/org/apache/syncope/client/console/authprofiles/AuthProfileDirectoryPanel_ru.properties
=> Fix: fix typo in message bundle

core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/RealmLogic.java, core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/TaskLogic.java
https://issues.apache.org/jira/browse/SYNCOPE-1867
Decided to do a PR after all just to be extra safe. I did also examine all other instances of this usage in all logic methods and so far, it appears that this was the only occurrence of this error.
=> SYNCOPE-1867: Prevent NPE when fetching realm entitlements

core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/DelegationLogic.java, core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/content/XMLContentExporter.java, core/persistence-neo4j/src/main/java/org/apache/syncope/core/persistence/neo4j/content/XMLContentExporter.java, core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/utils/TemplateUtils.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/AuthenticationITCase.java, fit/core-reference/src/test/java/org/apache/syncope/fit/core/RealmITCase.java
- Updates instances where a `containsKey` can be directly used on a `Map` instead of its `entrySet()`
- Removes `contains` calls on `Set` collections prior to adding elements; `contains` is implied and sets ignore duplicate elements.
=> Chore: update redundant collection ops (contains, add)

client/idrepo/console/src/main/java/org/apache/syncope/client/console/policies/PolicyModalPanelBuilder.java
**Account policy**: set input for `maxAuthenticationAttempts` required and with min value set to 0
**Password policy**: set input for `historyLength` required and with min value set to 0
**Propagation policy**: set input for `maxAttempts` required
=> [SYNCOPE-1888] Change required property for specific inputs in policy configuration
