client/console/src/main/java/org/apache/syncope/client/console/rest/AnyTypeRestClient.java
client/console/src/main/java/org/apache/syncope/client/console/wizards/resources/ResourceProvisionPanel.java

Hi,
this fixes [[SYNCOPE-1154]](https://issues.apache.org/jira/browse/SYNCOPE-1154)
Regards,
Matteo

Keep resource provision list order after editing for SYNCOPE-1154

---

client/enduser/src/main/resources/META-INF/resources/app/views/self.html

spostato menù saml e aggiunta stringa informativa

SYNCOPE-1197 SAML label inserted and combo moved below login button

---

client/console/src/main/java/org/apache/syncope/client/console/wizards/any/PlainAttrs.java

Fix for issue [SYNCOPE-1439](https://issues.apache.org/jira/browse/SYNCOPE-1439) on version `2.0.x`.

[SYNCOPE-1439] Fixed user membership attributes not updating from Admin Console

---

.travis.yml
pom.xml

See title please.
After a few tries, passing build on local fork: https://travis-ci.org/mmoayyed/syncope/builds/588965303

NOJIRA: Update gmavenplus-plugin version & fix CI failures

---

common/idrepo/lib/src/main/java/org/apache/syncope/common/lib/to/TaskTO.java
core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/NotificationLogic.java
core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/TaskLogic.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/TaskDataBinderImpl.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/AbstractTaskITCase.java

Also make sure FITs have test cases that enforces this.

SYNCOPE-1465: make sure task objects track the executor.

---

core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/content/XMLContentLoader.java

Disallow Doctypes for SAXParserFactory

Disallow Doctypes for SAXParserFactory

---

client/console/src/main/java/org/apache/syncope/client/console/commons/status/StatusUtils.java
client/console/src/main/java/org/apache/syncope/client/console/panels/ConnObjectListViewPanel.java
client/console/src/main/java/org/apache/syncope/client/console/panels/ConnObjects.java
client/console/src/main/java/org/apache/syncope/client/console/status/AnyStatusDirectoryPanel.java
client/console/src/main/java/org/apache/syncope/client/console/status/ReconTaskPanel.java
client/console/src/main/java/org/apache/syncope/client/console/status/ResourceStatusDirectoryPanel.java
client/console/src/main/resources/META-INF/resources/css/syncopeConsole.css
client/console/src/main/resources/org/apache/syncope/client/console/panels/ListViewPanel.html
client/console/src/main/resources/org/apache/syncope/client/console/status/ReconTaskPanel.html
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/utils/ConnObjectUtils.java

Fixes [SYNCOPE-1500] in the 2_1_X branch

[SYNCOPE-1500] Allow single import from External Resource

---

fit/core-reference/src/test/java/org/apache/syncope/fit/console/AnyObjectsITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/console/GroupsITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/console/PoliciesITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/console/UsersITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/AuditITCase.java

Fixes a number of tests related to recent changes to the wicket layouts and menus. Also cleans up audit ITs.

SYNCOPE-1511: Test fixes

---

core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/JPAConnInstanceDAO.java

See https://issues.apache.org/jira/browse/SYNCOPE-1523

SYNCOPE-1523: JPAConnInstanceDAO: mark find()/authFind() methods as Transactional

---

ext/flowable/flowable-bpmn/src/main/java/org/apache/syncope/core/flowable/task/Suspend.java

(cherry picked from commit 4d2398c54bf558db37b1fa675b693bfe9e5fc54d)

allow flowable suspend to set user suspension

---

.travis.yml
fit/core-reference/src/main/resources/all/saml2sp-logic.properties

Improving Travis CI

---

common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/JDBCAuthModuleConf.java
common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/LDAPAuthModuleConf.java
core/am/logic/src/main/java/org/apache/syncope/core/logic/AuthModuleLogic.java
core/persistence-jpa/src/test/resources/domains/MasterContent.xml
wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/SyncopeWAPropertySourceLocator.java

TODO:
- Translate profile item mappings for attributes, etc.
- Fix configuration data and tests for AuthModuleITs to not bootstrap the context with invalid state/configuration.

SYNCOPE-1553: Translate AuthModuleConfs to WA

---

core/persistence-jpa-json/src/test/resources/domains/MasterContent.xml
core/persistence-jpa/src/test/resources/domains/MasterContent.xml
docker/wa/src/main/resources/application.properties
docker/wa/src/main/resources/wa.properties
fit/wa-reference/src/main/resources/wa.properties
pom.xml
wa/starter/pom.xml
wa/starter/src/main/resources/application.properties
wa/starter/src/main/resources/wa.properties

- Updates context to ensure GoogleAuth settings are properly defined, reloaded and refreshed.
- Latest snapshots of CAS contain fixes to be able to handle reloads for GoogleAuth components
- Updates WA/Application properties to specify props using recommended kebab-case syntax.
Screenshot:

SYNCOPE-1559: Support GoogleAuth MFA configuration

---

ext/flowable/client-console/src/main/java/org/apache/syncope/client/console/panels/UserRequestFormDirectoryPanel.java

Do not initialize user approval form with the password taken from workflow

[SYNCOPE-1563] Fixed password mangement in user approval form

---

common/keymaster/client-api/src/main/resources/defaultContent.xml
core/persistence-jpa-json/src/main/resources/domains/MasterContent.xml
core/persistence-jpa-json/src/test/resources/domains/MasterContent.xml
core/persistence-jpa/src/main/resources/domains/MasterContent.xml
core/persistence-jpa/src/test/resources/domains/MasterContent.xml
core/persistence-jpa/src/test/resources/domains/TwoContent.xml
core/provisioning-api/src/test/java/org/apache/syncope/core/provisioning/api/jexl/MailTemplateTest.java
docker/core/src/main/resources/domains/MasterContent.xml.all
docker/core/src/main/resources/domains/MasterContent.xml.myjson
docker/core/src/main/resources/domains/MasterContent.xml.pgjsonb

"was request for" -> "was requested for"

Fixing a grammatical issue with the mail template

---

common/am/lib/src/main/java/org/apache/syncope/common/lib/to/client/CASSPTO.java
core/am/logic/src/main/java/org/apache/syncope/core/logic/ClientAppLogic.java
core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/dao/auth/CASSPDAO.java
core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/auth/CASSP.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/dao/auth/JPACASSPDAO.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/JPAEntityFactory.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/auth/JPACASSP.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/auth/JPAClientAppUtilsFactory.java
core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/CASSPTest.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/ClientAppDataBinderImpl.java
fit/core-reference/src/test/java/org/apache/syncope/fit/AbstractITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/ClientAppITCase.java
wa/starter/src/main/java/org/apache/syncope/wa/starter/mapping/CASSPTOMapper.java

Cf. https://issues.apache.org/jira/browse/SYNCOPE-1577

SYNCOPE-1577: Support CAS protocol for client applications

---

fit/wa-reference/src/main/resources/wa.properties
pom.xml
wa/starter/pom.xml
wa/starter/src/main/resources/wa.properties

https://issues.apache.org/jira/browse/SYNCOPE-1587
Adds baseline support for WA. Device registration and management APIs may be done in a separate pull request.

SYNCOPE-1587: WA Web AuthN MFA support

---

pom.xml
wa/starter/src/main/java/org/apache/syncope/wa/starter/saml/idp/metadata/RestfulSamlIdPMetadataLocator.java

- Running CI based on the latest CAS SNAPSHOT to remove NPE issues preventing WA/SRA tests to run successfully.
- Reducing noise in logs when SAML IDP metadata cannot be found.

NOJIRA: Fix ITs for SRA/WA

---

wa/starter/src/main/java/org/apache/syncope/wa/starter/webauthn/SyncopeWAWebAuthnCredentialRepository.java

Fixed a component import reference in WebAuthn implementation after upgrading to WebAuthN 1.7.0. This PR will be revisited once the upgrade is publicly available in the coming snapshots

NOJIRA: Fix WebAuthN component import reference

---

common/am/lib/src/main/java/org/apache/syncope/common/lib/auth/DuoMfaAuthModuleConf.java
core/persistence-jpa-json/src/test/resources/domains/MasterContent.xml
core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/AuthModuleTest.java
core/persistence-jpa/src/test/resources/domains/MasterContent.xml
fit/core-reference/src/test/java/org/apache/syncope/fit/core/AuthModuleITCase.java
pom.xml
wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/SyncopeWAPropertySourceLocator.java
wa/starter/pom.xml

JIRA: https://issues.apache.org/jira/browse/SYNCOPE-1599
Baseline support for duo security as an mfa solution. Next RC will also provide support for [Universal Prompt](https://duo.com/docs/oauthapi).
Marking as WIP for now to let CI do its job.

SYNCOPE-1599: support for duo security mfa

---

pom.xml
wa/starter/pom.xml
wa/starter/src/main/java/org/apache/syncope/wa/starter/webauthn/SyncopeWAWebAuthnCredentialRepository.java

Also fixes a number of minor issues regarding WebAuthN JSON serialization components.

Upgrade WA to use CAS v6.3.0-RC5

---

core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/PGJPAJSONAnySearchDAO.java
core/persistence-jpa-json/src/main/java/org/apache/syncope/core/persistence/jpa/dao/PGJPAJSONPlainSchemaDAO.java
core/persistence-jpa-json/src/main/resources/pgjsonb/views.xml
docker/src/main/resources/docker-compose/docker-compose-ha.yml
docker/src/main/resources/docker-compose/docker-compose-pgjsonb.yml
docker/src/main/resources/docker-compose/docker-compose-postgresql.yml
pom.xml

Improve queries in order to avoid table joins

[SYNCOPE-1609] Changes jsonb queries in order to improve performances

---

docker/wa/src/main/resources/wa.properties
fit/wa-reference/src/main/resources/wa.properties
wa/starter/src/main/resources/wa.properties
wa/starter/src/test/resources/debug/wa.properties

This is a preparatory pull request, in anticipation of the changes going into the next 6.4 SNAPSHOT, early next week that affect openid connect configuration schema and properties.

Move OIDC properties to required namespaces in config

---

.github/workflows/crosschecks.yml
.github/workflows/fit_Payara.yml
.github/workflows/fit_Tomcat_H2_JSON.yml
.github/workflows/fit_Tomcat_H2_XML.yml
.github/workflows/fit_Tomcat_H2_YAML.yml
.github/workflows/fit_WA_SAML2PS4UI_OIDCC4UI.yml
.github/workflows/fit_WA_SRA_CASClient.yml
.github/workflows/fit_WA_SRA_OAuth2.yml
.github/workflows/fit_WA_SRA_OIDC.yml
.github/workflows/fit_WA_SRA_SAML2.yml
.github/workflows/fit_Wildfly.yml
.travis.yml
archetype/src/main/resources/archetype-resources/fit/pom.xml
archetype/src/main/resources/meta-pom.xml
fit/build-tools/pom.xml
fit/build-tools/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
fit/console-reference/pom.xml
fit/core-reference/pom.xml
fit/core-reference/src/main/resources/application-wildfly.properties
fit/core-reference/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
fit/enduser-reference/pom.xml
fit/wa-reference/pom.xml
pom.xml
src/main/asciidoc/getting-started/systemRequirements.adoc
src/main/asciidoc/reference-guide/workingwithapachesyncope/systemadministration/javaeecontainer.adoc
standalone/pom.xml

Attempting to solve the problems raised in [this ML thread](https://lists.apache.org/thread.html/913b0e77db9d5bb346a24cd85d9b4393e383700a7998ab249af703f4%40%3Cdev.syncope.apache.org%3E).

Removing ianal-maven-plugin for Geronimo's tools-maven-plugin

---

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/UserDataBinderImpl.java

Signed-off-by: Dmitriy Brashevets <dmitriy.brashevets@united-security-providers.ch>

[SYNCOPE-1643] Chaning of user realm doesn't trigger provisioning

---

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/AbstractPullResultHandler.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/DefaultUserPullResultHandler.java
fit/core-reference/src/test/java/org/apache/syncope/fit/AbstractITCase.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/PullTaskITCase.java

Also made some refactoring to `AbstractPullResultHandler` and `DefaultUserPullResultHandler`

[SYNCOPE-1656] remediation now is generated also on pull update failure

---

core/idrepo/logic/src/main/java/org/apache/syncope/core/logic/UserLogic.java
core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/user/Account.java
core/persistence-api/src/main/java/org/apache/syncope/core/persistence/api/entity/user/User.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/user/JPALinkedAccount.java
core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/entity/user/JPAUser.java
core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/MultitenancyTest.java
core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/inner/UserTest.java
core/persistence-jpa/src/test/java/org/apache/syncope/core/persistence/jpa/outer/UserTest.java
core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/data/UserDataBinder.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/DefaultMappingManager.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/UserDataBinderImpl.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/propagation/DeletingLinkedAccount.java
core/provisioning-java/src/test/java/org/apache/syncope/core/provisioning/java/DefaultMappingManagerTest.java
core/spring/src/main/java/org/apache/syncope/core/spring/policy/DefaultPasswordRule.java
core/spring/src/main/java/org/apache/syncope/core/spring/policy/HaveIBeenPwnedPasswordRule.java
ext/flowable/logic/src/main/java/org/apache/syncope/core/logic/UserRequestLogic.java
fit/core-reference/src/main/java/org/apache/syncope/fit/core/reference/TestPasswordRule.java
src/main/asciidoc/reference-guide/configuration/configurationparameters.adoc

[SYNCOPE-1666] added security answer hashing

[SYNCOPE-1666] added security answer hashing (#319)

---

docker/console/pom.xml
docker/console/src/main/resources/Dockerfile
docker/core/pom.xml
docker/core/src/main/resources/Dockerfile
docker/enduser/pom.xml
docker/enduser/src/main/resources/Dockerfile
docker/sra/pom.xml
docker/sra/src/main/resources/Dockerfile
docker/wa/pom.xml
docker/wa/src/main/resources/Dockerfile

In particular, produce images compatible with ARM architectures.

Support multi-arch docker builds

---

core/idrepo/rest-cxf/src/main/java/org/apache/syncope/core/rest/cxf/service/AbstractService.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/UserIssuesITCase.java

Please see https://issues.apache.org/jira/browse/SYNCOPE-1699

SYNCOPE-1699: Extract key from path  if undefined in request body

---

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/AbstractPullResultHandler.java
core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/pushpull/DefaultUserPullResultHandler.java

Skip delete operation in case of NO_MATCH

[SYNCOPE-1755] Skip delete operation in case of NO_MATCH

---

wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WABootstrapConfiguration.java
wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAPropertySourceLocator.java

SYNCOPE-1765: allow WA properties to be decrypted

---

core/spring/src/main/java/org/apache/syncope/core/spring/security/DefaultPasswordGenerator.java
ext/oidcc4ui/logic/src/main/java/org/apache/syncope/core/logic/oidc/OIDCC4UIContext.java
ext/saml2sp4ui/logic/src/main/java/org/apache/syncope/core/logic/saml2/SAML2SP4UIContext.java
fit/core-reference/pom.xml
pom.xml
sra/src/main/java/org/apache/syncope/sra/security/pac4j/ServerWebExchangeContext.java
wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAProperties.java
wa/starter/src/main/java/org/apache/syncope/wa/starter/config/WAContext.java
wa/starter/src/main/resources/wa.properties
wa/starter/src/test/resources/debug/log4j2.xml
wa/starter/src/test/resources/debug/wa-debug.properties

Background: https://github.com/spring-projects/spring-security/issues/13988

Align with upstream CAS

---

client/idrepo/console/src/main/resources/console.properties
client/idrepo/enduser/src/main/resources/enduser.properties
core/starter/src/main/resources/core.properties
pom.xml
sra/src/main/resources/sra.properties
wa/starter/src/main/resources/wa.properties

As mentioned by Spring Boot 3.2 [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-Release-Notes#support-for-virtual-threads) it seems you have to explicitly enable virtual threads support.

Upgrading Spring Boot

---

.github/workflows/crosschecks.yml
pom.xml

This requires https://github.com/apache/cxf/pull/1972

Checking compatibility with JDK23

---

core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/serialization/POJOHelper.java
core/provisioning-api/src/main/java/org/apache/syncope/core/provisioning/api/serialization/PropagationTaskInfoSerializer.java
core/provisioning-api/src/test/java/org/apache/syncope/core/provisioning/api/serialization/PropagationTaskInfoSerializerTest.java

…tion errors, especially on audit

[SYNCOPE-1847] added PropagationTaskInfoSerializer to avoid serialization errors, especially on audit

---

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/data/GroupDataBinderImpl.java
fit/core-reference/src/test/java/org/apache/syncope/fit/core/UserIssuesITCase.java

* [SYNCOPE-1853] Avoid unwanted user/any object propagation on group delete

SYNCOPE-1853 avoid unwanted user/any deprovision on group delete (#958)

---

core/provisioning-java/src/main/java/org/apache/syncope/core/provisioning/java/DefaultUserProvisioningManager.java

[SYNCOPE-1868] avoid NPE when performing provision without changing password
